services:
  headscale:
    image: headscale/headscale:0.22.3
    restart: unless-stopped
    container_name: headscale
    ports:
      - "0.0.0.0:8080:8080"
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config/headscale:/etc/headscale
      - headscale_data:/var/lib/headscale
    tmpfs:
      - /var/run
    command: headscale serve
