services:
  headscale:
    image: headscale/headscale:0.22.3
    restart: unless-stopped
    container_name: headscale
    ports:
      - "8080:8080"
    volumes:
      - ./config/headscale:/etc/headscale
      - headscale_data:/var/lib/headscale
    tmpfs:
      - /var/run
    command: headscale serve

volumes:
  headscale_data:
